// File autogenerated by `./autogen.sh`, do not edit
#ifndef MEASUREMENT_KIT_COMMON_GIT_VERSION_HPP
#define MEASUREMENT_KIT_COMMON_GIT_VERSION_HPP

#define MK_VERSION_FULL "v0.9.0-dev-7-g72260e40"

#endif
